id = "forester"
name = "Forester"
version = "0.0.1"
schema_version = 1
authors = ["Owen Lynch <root@owenlynch.org>"]
description = "Extension for forester integration"
repository = "https://github.com/olynch/forester-zed"

[grammars.forester]
repository = "https://github.com/olynch/tree-sitter-forester/"
commit = "fa78984cc7d4f53c319d398c950072ca1388e7e0"

# [language_servers.forester]
# name = "Forester LSP"
# languages = ["Forester"]
